### PR TITLE
Plugin for webhook notifications

### PR DESCRIPTION
**Pull request by seanhandley**
Simple plugin to push custom payloads to a webhook URL.

This is handy for people who integrate apps like Hipchat, Campfire or Slack into their development workflows.

To do:

- [ ] Testing
- [ ] More interpolatable variables

### CODE REVIEW

**Comment by Zapotek** [comment]
Thanks Sean.

I'll need to update it to use `Arachni::HTTP::Client` instead of `Net::HTTP` but it looks good.

**Comment by seanhandley** [comment]
Ah ok I can probably do that! I'll take a look after the weekend.

We're setting Arachni up for periodic pen tests but we tend to use Slack for notifications.

Is there an approximate target date for the 1.5 release?

**Comment by Zapotek** [comment]
You won't have to wait that long, as soon as it's ready and merged into experimental you'll be able to access it via the nightlies.
Btw, I see you've issued this against `master`, please switch to the `experimental` branch.

**Comment by seanhandley** [comment]
Done @Zapotek - Moved to #681

**Pull request closed without merging**
